spring.application.name=crm-ticketing-api

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Database Configuration
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/crm_ticketing_db?createDatabaseIfNotExist=true
db.username=root
db.password=root

# Hibernate Configuration
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update

# Hikari Configuration
spring.datasource.hikari.pool-name=HikariPool-CRM
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2 
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000


spring.kafka.bootstrap-servers=localhost:9092
spring.data.redis.host=localhost
spring.data.redis.port=6379